language: java

jdk:
- oraclejdk7



before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-1.0.$TRAVIS_BUILD_NUMBER.
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITPERM@github.com/dougmaitelli/GeometryLib --tags
  - ls -R

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $GITPERM
  file:
    - "README.md"
    - "GeometryLib-1.0.jar"
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-[0-9]/
